spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "0000"
    url: jdbc:mysql://127.0.0.1:3306/springimport_excel?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
      &serverTimezone=UTC&allowPublicKeyRetrieval=true
    hikari:
      connection-timeout: 1000
      validation-timeout: 1000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 3
      minimum-idle: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml